---
title: "AlisonProject"
author: "Alison Barbee"
date: "2022-12-14"
output: word_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, Alison}
library(tidytuesdayR)

```


#Adding Wildfire Data

```{r, Kate}
# Get the Data

rainfall <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/rainfall.csv')

temperature <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/temperature.csv')

# IF YOU USE THIS DATA PLEASE BE CAUTIOUS WITH INTERPRETATION

nasa_fire <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/MODIS_C6_Australia_and_New_Zealand_7d.csv')

# For JSON File of fires

url <- "http://www.rfs.nsw.gov.au/feeds/majorIncidents.json"

aus_fires <- sf::st_read(url)

# Or read in with tidytuesdayR package (https://github.com/thebioengineer/tidytuesdayR)

# Either ISO-8601 date or year/week works!

# Install via devtools::install_github("thebioengineer/tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load('2020-01-07') 
tuesdata <- tidytuesdayR::tt_load(2020, week = 2)


rainfall <- tuesdata$rainfall
```



Cleaning Data
```{r}
library(tidyverse)
library(here)

read_file_list <- list.files(here::here("2020", "2020-01-07")) %>% 
  .[str_detect(., "tmax|tmin")]

read_clean_temp_data <- function(file_name){
  
  temp_descrip <- if_else(str_detect(file_name, "min"), "min", "max")
  
  read_csv(here::here("2020", "2020-01-07", file_name)) %>% 
    janitor::clean_names() %>% 
    fill(site_name, site_number) %>% 
    filter(!is.na(date)) %>% 
    rename(temperature = contains("temp")) %>% 
    mutate(temp_type = temp_descrip)  %>% 
    mutate(city_name = word(site_name, 1)) %>%  
    select(city_name, date, temperature, temp_type, site_name)
  
}


# Get Clean Temp Data -----------------------------------------------------

clean_df <- read_file_list %>% 
  map(read_clean_temp_data) %>% 
  bind_rows()

write_csv(clean_df, here::here("2020", "2020-01-07","temperature.csv"))


##### Prep for Clean Rain Data
#####
#####

name_df <- tribble(
  ~station_code, ~city_name, ~lat, ~long, ~station_name,
  "009151", "Perth", -31.96, 115.79, "Subiaco Wastewater Treatment Plant",
  "023011", "Adelaide", -34.92, 138.6, "North Adelaide",
  "040383", "Brisbane", -27.51, 153.05, "Greenslopes Private Hospital",
  "040913", "Brisbane", -27.48, 153.04, "Brisbane",
  "066062", "Sydney", -33.86, 151.21, "Observatory Hill",
  "070351", "Canberra", -35.31, 149.2, "Canberra Airport",
  "086232", "Melbourne", -37.83, 144.98, "Melbourne Botanical Gardens"
)

read_precip_list <- list.files(here::here("2020", "2020-01-07")) %>% 
  .[str_detect(., "IDCJ")]

read_clean_precip_data <- function(file_name){
  
  read_csv(here::here("2020", "2020-01-07", file_name)) %>% 
    janitor::clean_names() %>% 
    select("station_code" = bureau_of_meteorology_station_number,
           year, month, day,
           "rainfall"= rainfall_amount_millimetres, 
           "period" = period_over_which_rainfall_was_measured_days,
           quality) %>% 
    mutate(station_code = as.character(station_code)) %>% 
    left_join(name_df, by = "station_code") %>% 
    select(station_code, city_name, everything())
  
}


# Get Clean Rain Data -----------------------------------------------------

clean_rain_df <- read_precip_list %>% 
  map(read_clean_precip_data) %>% 
  bind_rows()

write_csv(clean_rain_df, here::here("2020", "2020-01-07","rainfall.csv"))
```


```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(rgdal)
library(tmap)
library(ggmap)
library(dplyr)
library(ggspatial)
library(rlang)
library(broom)
library(tidyverse)
library(readxl)
library(purrr)

library(ozmaps)

url <- "http://www.rfs.nsw.gov.au/feeds/majorIncidents.json"

fires <- st_read(url)

fires

mapview(fires)

#' Hacky way to get rid of points within geometry collections
fire_poly <- fires %>% 
  st_buffer(dist = 0) %>% 
  st_union(by_feature = TRUE)

mapview(fire_poly)

fires %>% 
  mutate(pubdate = as.character(pubDate),
         pubdate = as.Date(pubdate))
```

```{r}
aus_stations <- name_df %>%
  dplyr::select(station_code, city_name, lat, long, station_name)

aus_stations <- st_as_sf(aus_stations, coords = c("lat", "long")) %>%
  st_set_crs(4283)

```

```{r}
library(sf)

aus_fires <- nasa_fire %>%
  dplyr::select(latitude, longitude, brightness, acq_date)

aus_fires <- st_as_sf(aus_fires, coords = c("longitude", "latitude")) %>%
  st_set_crs(4283)


```

```{r, stations}

ggplot() + 
  geom_sf(data = oz_states) + 
  geom_sf(data = aus_fires, colour = "red") + 
  coord_sf()
```

```{r, Australia fires}
library(sf)
library(tigris)
library(ggplot2)
library(viridis)
library(MAP)
library(ozmaps)

oz_states <- ozmaps::ozmap_states



ggplot() + 
  geom_sf(data = oz_states) + 
  geom_sf(data = aus_fires, colour = "red") + 
  coord_sf()
```

```{r, Leaflet}
library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  setView(130, -25, zoom = 4)

```

```{r, Perth}
library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  setView(115.79, -31.96, zoom = 6) %>%
  addMarkers(115.79, -31.96, popup = "Subiaco Wastewater Treatment Plant")


```

```{r, Adelaide}
library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  setView(138.6, -34.92, zoom = 6) %>%
  addMarkers(138.6, -34.92, popup = "North Adelaide")
 

```

```{r, Brisbane}
library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  setView(153.05, -27.51, zoom = 6) %>%
  addMarkers(153.05, -27.51, popup = "Greenslopes Private Hospital")


```

```{r, Brisbane2}
library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  setView(153.04, -27.48, zoom = 6) %>%
  addMarkers(153.04, -27.48, popup = "Brisbane")


```

```{r, Sydney}
library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  setView(151.21, -33.86, zoom = 6) %>%
  addMarkers(151.21, -33.86, popup = "Observatory Hill")


```

```{r, Canberra}
library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  setView(149.2, -35.31, zoom = 6) %>%
  addMarkers(149.2, -35.31, popup = "Canberra Airport")


```

```{r, Melbourne}
library(leaflet)

leaflet() %>% 
  addTiles() %>%  
  setView(144.98, -37.83, zoom = 6) %>%
  addMarkers(144.98, -37.83, popup = "Melbourne Botanical Gardens")


```


```{r}
write_csv(aus_stations, "aus_stations.csv")
```


