---
title: "Temperature and Rainfall Plots"
author: "Kate Bazany"
date: "2022-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
```


# Loading the data

```{r, Kate}
rainfall <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/rainfall.csv')
temperature <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/temperature.csv')
```


# Cleaning Rainfall Data

```{r}
clean_rain_df_3 <- rainfall %>%
  filter(year > 2009) %>%
  mutate(year_month = paste(year, month, sep = "-")) %>%
  mutate(year_month = ym(year_month)) %>%
  group_by(station_code, city_name, lat, long, station_name, year_month) %>%
  summarize(monthly_rain = sum(rainfall)) 
```

# Plot of monthly total rainfall from 2010 to 2020

```{r}
rain_plot_monthly <- clean_rain_df_3 %>%
  ggplot() +
  geom_point(aes(x = year_month, y = monthly_rain), 
             color = "blue", alpha = .8, size = .1) + 
  geom_smooth(aes(x = year_month, y = monthly_rain), color = "black") +
  facet_wrap(vars(city_name)) +
  theme_classic() + ylab("Total Monthly Rainfall (cm)") + xlab("Date (year)")
rain_plot_monthly
```

# Cleaning Temperature Data

```{r}
temperature$temperature <- as.integer(temperature$temperature)
clean_temp_df <- temperature %>%
  group_by(city_name, temp_type, site_name, date) %>%
  summarize(average_temp = mean(temperature, na.rm = TRUE)) %>%
  pivot_wider(names_from = temp_type, values_from = average_temp)

clean_temp_df_all <- temperature %>% 
  pivot_wider(names_from = temp_type, values_from = temperature)
clean_temp_df_all$year <- substr(clean_temp_df_all$date, 1, 4)
clean_temp_df_10 <- clean_temp_df_all %>%
  filter(year > 2009)
```

# Plot of maximum and minimum temperatures from 2010 to 2020

```{r}
temp_plot_10 <- clean_temp_df_10 %>%
  ggplot() +
  geom_point(aes(x = date, y = max), size = .1, alpha = .05, color = "red") +
  geom_point(aes(x = date, y = min), size = .1, alpha = .05, color = "orange") +
  geom_smooth(aes(date, max), color = "red") +
  geom_smooth(aes(date, min), color = "orange") +
  facet_wrap(vars(city_name)) +
  theme_classic() + ylab("Max and Min Temp (C)") + xlab("Date (year)")
temp_plot_10 
```
